name: Test Palisade Action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Palisade Action (local)
        uses: ./
        with:
               args: "track-provenance ./models"

      # - name: Upload ML-BOM
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ml-bom
      #     path: ML-BOM.json


