name: Test Palisade Action

on:
  push :
    branches:
      - devops-rev
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Palisade Action (local)
        uses: ./
        with:
            args: "scan . --format sarif --output palisade.sarif"

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: palisade.sarif


